import React from "react";
import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";
import TopPageMovie from "./components/TopPageMovie";

export default function Home() {
  return (
    <MainContainerArea>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <TopPageMovie />
        <SubContainerArea>
          <Title>i think...</Title>
          <Paragraph>
            <SpanArea>
              好きな色 好きな街 好きな空 好きな店 好きな人
              人の心は、いろんな「好き」でできている
            </SpanArea>
          </Paragraph>
          <Paragraph>
            <SpanArea>
              それぞれの想いを 写真として 映像として ブランドや世界観を体現し
              人の心に届ける
            </SpanArea>
          </Paragraph>
          <Paragraph>
            <SpanArea>
              時間を超えて本当に良いものを 記録に残すこと
              時間とともに変わる世界を 記録に残すこと
            </SpanArea>
          </Paragraph>
          <Paragraph>
            <SpanArea>
              記録は記憶を鮮やかにする 写真を見て懐かしい気持ちを思い出すように
            </SpanArea>
          </Paragraph>
          <Paragraph>
            <SpanArea>
              さぁ まだ想像したこともない カラフルな世界へ踏み出そう
            </SpanArea>
          </Paragraph>
        </SubContainerArea>
      </main>

      <BasicFooter>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <SpanArea>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </SpanArea>
        </a>
      </BasicFooter>
    </MainContainerArea>
  );
}

const MainContainerArea = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  min-height: 100vh;
  padding: 0 0.5rem;
  text-align: center;
`;

const SubContainerArea = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  min-height: 100vh;
  padding: 0 0.5rem;
  text-align: center;
`;

const Title = styled.h1`
  margin: 0;
  line-height: 1.15;
  font-size: 4rem;
`;

const Paragraph = styled.p`
  line-height: 1.5;
  font-size: 1rem;
`;

const SpanArea = styled.span`
  color: #0070f3;
  text-decoration: none;
`;

const BasicFooter = styled.footer`
  width: 100%;
  max-width: 1200px;
  margin: 0 auto;
  padding: 0 1rem;
`;
